### PR TITLE
Batch smie fixes

### LINKED ISSUE #60: Indention bug: return statement with ternary operator
Hi,

a ternary operator is a common thing in return statements, and often they contain line breaks. A ternary operator should therefore be indented:

instead of this (current behaviour):

``` swift
return order!.deliver ?
OrderViewTableDeliveryCells.lastCellIndex.rawValue :
OrderViewTableTakeAwayCells.LastCellIndex.rawValue
```

I'd like to get this:

``` swift
return order!.deliver ?
  OrderViewTableDeliveryCells.lastCellIndex.rawValue :
  OrderViewTableTakeAwayCells.LastCellIndex.rawValue
```

### PR DESCRIPTION
**Pull request by ap4y**
Batch of improvements for the issues raised in #74. Also fixes #60, #73, #58, #77, #80, #81.

### CODE REVIEW

**Comment by ap4y** [comment]
Don't have emacs 23 atm. Will check failing tests in VM tomorrow, will take some time.

**Comment by bbatsov** [comment]
Emacs 23 doesn't support lexical scoping and has a super outdated SMIE, so we shouldn't care about it.

**Comment by ap4y** [comment]
I meant emacs `24.3`, oops :) It still has a quite significant difference with `24.4`. Not sure what is preferred way of handling this... How does emacs trunk tests `smie` based modes? It's a bit hard for me to backport some changes to `24.3` (specifically nested hashes), previously I changed tests to a different form, but I don't think it's a right solution.

**Comment by bbatsov** [comment]
> How does emacs trunk tests smie based modes?

They don't care about older versions there. We can drop support for 24.3 - 24.4 is out and installing it isn't hard on most systems.

**Comment by ap4y** [comment]
This honestly would be awesome. I will try to fix it tomorrow, only 4 tests are failing at the moment on `24.3`. If it will be hard to do, I will disable travis tests against `24.3`. In this case we should change required version [here](https://github.com/chrisbarrett/swift-mode/blob/master/swift-mode.el#L9), right?

**Comment by bbatsov** [comment]
Yes. I'm pretty sure the mode isn't working well on 24.1 and 24.2 anyways.
:-)

On 26 January 2015 at 09:16, Arthur Evstifeev <notifications@github.com>
wrote:

> This honestly would be awesome. I will try to fix it tomorrow, only 4
> tests are failing at the moment on 24.3. If it will be hard to do, I will
> disable travis tests against 24.3. In this case we should change required
> version here
> <https://github.com/chrisbarrett/swift-mode/blob/master/swift-mode.el#L9>,
> right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chrisbarrett/swift-mode/pull/76#issuecomment-71421892>
> .
>



-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by taku0** [comment]
`swift-smie--decl-specifier-regexp` is broken because `(rx "(?=[[:space:]]*func)")` results `"(\\?=\\[\\[:space:]]\\*func)"`

**Comment by ap4y** [comment]
Yeah, I forgot emacs doesn't have lookaheads.

**Comment by ap4y** [comment]
Hey @bbatsov or @taku0, can I ask you to review this PR. Sorry it has so many commits and it took so long, but it fixes quite a few issues raised by @taku0 and many others. It also provides alternative solution to what @taku0 did in #74. I didn't change cases that are qualified as personal preferences. I would prefer to address those cases in separate PR with possibility of adding customizable parameters. I hope I didn't miss any issues here, but if that happened feel free to create a new issue or re-open a previous one. 

I tried to preserve support for the emacs 24.3, unfortunately it wasn't possible for 3 test cases. For some reason emacs 24.3 treats parent based indentation rules differently (I actually think it's a bug), so I had to make assertions conditional. This sounds a bit gross, so I'm keen to hear other opinions about what should we do in this case.

**Comment by bbatsov** [comment]
I'll have a look at the code.

> I tried to preserve support for the emacs 24.3, unfortunately it wasn't possible for 3 test cases. For some reason emacs 24.3 treats parent based indentation rules differently (I actually think it's a bug), so I had to make assertions conditional. This sounds a bit gross, so I'm keen to hear other opinions about what should we do in this case.

As many modes started to adopt smie in 24.4 a lot of bugs were fixed then. I'm fine with dropping 24.3 support altogether. As I said before - the upgrade path is trivial on all operating systems.

**Comment by taku0** [comment]
It seems that there are almost no problems for practical use.

Some cases we should handle better:

```swift
let foo =
    bar +
  baz +
  a

enum Foo: Bar {
    case foo
    case bar
        var foo
}

let foo = [
    bar:
    baz, // I want an extra indentation for this line
    bar:
    baz, // and this line
]

enum Foo {
    case A(Int, [Int : String]), B, C
                                    func foo() {
    }
}

@Foo public class Foo {
         a
     }
```

**Comment by ap4y** [comment]
Thanks @bbatsov, I will update my PR today with support for `24.4` only. 

Thanks @taku0 for checking PR once again, I would appreciate if you will create a separate issues for all the cases I missed or you think have to behave differently.

**Comment by ap4y** [comment]
@bbatsov this should be ready to merge.

**Comment by bbatsov** [comment]
Yeah, everything looks good! Great work, @ap4y! You'll soon give XCode a run for its money! :-)

**Comment by ap4y** [comment]
Haha thanks :)  XCode indentation engine is a complete disaster imo. I'm going to close some issues, github doesn't support list of references, so will do it manually.

**Pull request merged**
