### PR TITLE
Failing test idents-class-func-declaration/2/1: indentation error in class/function body...

### PR DESCRIPTION
**Pull request by dougbeal**
... when function has no modifiers
Issue #81

### CODE REVIEW

**Comment by dougbeal** [comment]
Is this the right way to report a bug with tests?

**Comment by ap4y** [comment]
Yeah, that's fine, I will merge it once #76 is ready. Thanks.

**Comment by dougbeal** [comment]
It passes without override, but fails with it.  This is the opposite of what it was doing before.
````
class Foo: Bar {
    func Foo() {
|foo
    }
}
```
```
class Foo: Bar {
    override func Foo() {
|foo
    }
}
```
2 unexpected results:
   FAILED  indentation/indents-class-func-declaration/2/2
   FAILED  indentation/indents-protocol-declaration/4

**Comment by ap4y** [comment]
Ok I will fix it as a part of #76

**Comment by ap4y** [comment]
Thanks again @dougbeal, test was merged in #76.

**Pull request closed without merging**
